"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect,useState } from "react";
import type { EnrollmentHistory,EnrollmentObservation } from "../../../lib/data/enrollment";

const WIDTH=900,HEIGHT=280,PADDING=34;
function pointsFor(values:number[],max:number){const innerWidth=WIDTH-PADDING*2,innerHeight=HEIGHT-PADDING*2,denominator=Math.max(1,values.length-1);return values.map((value,index)=>`${PADDING+(index/denominator)*innerWidth},${HEIGHT-PADDING-(value/Math.max(1,max))*innerHeight}`).join(" ");}
function EnrollmentChart({observations,code}:{observations:EnrollmentObservation[];code:string}){
  const max=Math.max(1,...observations.flatMap(point=>[point.enrolled,point.capacity,point.waitlisted])),start=observations[0],end=observations.at(-1);
  return <figure className="history-chart"><figcaption><div><h2>Seat movement</h2><p>{observations.length} verified observation{observations.length===1?"":"s"}</p></div><div className="chart-legend"><span className="enrolled-key">Enrolled</span><span className="capacity-key">Capacity</span><span className="waitlist-key">Waitlist</span></div></figcaption><svg viewBox={`0 0 ${WIDTH} ${HEIGHT}`} role="img" aria-label={`Enrollment history for ${code}: ${start.enrolled} to ${end?.enrolled??start.enrolled} enrolled, latest capacity ${end?.capacity??start.capacity}, and latest waitlist ${end?.waitlisted??start.waitlisted}.`}><line x1={PADDING} y1={HEIGHT-PADDING} x2={WIDTH-PADDING} y2={HEIGHT-PADDING}/><line x1={PADDING} y1={PADDING} x2={PADDING} y2={HEIGHT-PADDING}/>{observations.length===1?<circle className="chart-enrolled" cx={WIDTH/2} cy={HEIGHT-PADDING-(start.enrolled/max)*(HEIGHT-PADDING*2)} r="7"/>:<><polyline className="chart-capacity" points={pointsFor(observations.map(point=>point.capacity),max)}/><polyline className="chart-enrolled" points={pointsFor(observations.map(point=>point.enrolled),max)}/><polyline className="chart-waitlist" points={pointsFor(observations.map(point=>point.waitlisted),max)}/></>}</svg><div className="chart-axis"><span>{new Date(start.observedAt).toLocaleString()}</span><span>{end?new Date(end.observedAt).toLocaleString():""}</span></div></figure>;
}
function signed(value:number){return `${value>0?"+":""}${value}`;}
function velocity(value:number|null){return value===null?"Collecting":`${value>0?"+":""}${value.toFixed(1)}/day`;}

export default function EnrollmentPage(){
  const params=useParams<{sectionId:string}>(),[history,setHistory]=useState<EnrollmentHistory|null>(null),[error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();fetch(`/api/enrollment/${encodeURIComponent(params.sectionId)}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(response.status===404?"Section not found":"Live history is temporarily unavailable");return response.json() as Promise<EnrollmentHistory>;}).then(setHistory).catch(cause=>{if(cause.name!=="AbortError")setError(cause.message);});return()=>controller.abort();},[params.sectionId]);
  if(error)return <main className="history-state"><div><span className="kicker">ENROLLMENT INTELLIGENCE</span><h1>History unavailable.</h1><p>{error}</p><Link href="/catalog">Return to catalog</Link></div></main>;
  if(!history)return <main className="history-state" aria-live="polite">Loading verified enrollment history…</main>;
  const {section,observations,insights,provenance}=history,latest=observations.at(-1);
  return <main className="history-page"><section className="history-hero"><div><span className="kicker">{section.term} · SECTION {section.sectionNumber}</span><h1>{section.code}<br/><em>{section.title}</em></h1><p>{section.component??"Section"} · {section.instructors.join(", ")||"Instructor TBA"}</p></div><div className={`trend-badge ${insights.trend}`}><span>Current trend</span><strong>{insights.trend}</strong></div></section><section className="history-shell"><div className="history-metrics"><article><span>Open seats</span><strong>{insights.availableSeats}</strong><small>{latest?`${latest.enrolled} of ${latest.capacity} enrolled`:"No observation"}</small></article><article><span>Enrollment change</span><strong>{signed(insights.enrolledDelta)}</strong><small>Across retained history</small></article><article><span>Waitlist change</span><strong>{signed(insights.waitlistDelta)}</strong><small>{latest?`${latest.waitlisted} waiting now`:"No observation"}</small></article><article><span>Enrollment velocity</span><strong>{velocity(insights.velocityPerDay)}</strong><small>{insights.estimatedDaysToFill===null?"No reliable fill estimate":`≈ ${insights.estimatedDaysToFill.toFixed(1)} days to fill`}</small></article></div>{observations.length>0?<EnrollmentChart observations={observations} code={section.code}/>:<div className="history-empty">The section exists, but its first enrollment observation has not arrived yet.</div>}{observations.length<2?<aside className="history-notice"><b>Trend accumulating</b><p>CourseFlow has one verified observation for this section. The production refresh runs every 15 minutes; velocity and fill estimates appear only after real movement is measured.</p></aside>:null}<section className="history-evidence"><div><span className="kicker">DATA RECEIPT</span><h2>Transparent by design</h2><p>Latest observation: {new Date(provenance.latestObservedAt).toLocaleString()}. Source data is retained in Neon so changes can be measured over time.</p></div><dl><div><dt>Source</dt><dd><a href={provenance.sourceUrl}>{provenance.sourceName} ↗</a></dd></div><div><dt>Official source</dt><dd>{provenance.official?"Yes":"No — transitional adapter"}</dd></div><div><dt>Refresh cadence</dt><dd>Every 15 minutes</dd></div><div><dt>Samples retained here</dt><dd>{observations.length}</dd></div></dl></section><details className="history-table"><summary>View accessible observation table</summary><div><table><caption>Enrollment observations for {section.code}, section {section.sectionNumber}</caption><thead><tr><th>Observed</th><th>Enrolled</th><th>Capacity</th><th>Waitlisted</th></tr></thead><tbody>{observations.map(point=><tr key={point.observedAt}><td>{new Date(point.observedAt).toLocaleString()}</td><td>{point.enrolled}</td><td>{point.capacity}</td><td>{point.waitlisted}</td></tr>)}</tbody></table></div></details></section></main>;
}
