"use client";
import { useEffect,useMemo,useState } from "react";
import { letterGradeOrder,type GradeDetail } from "../lib/grade-types";

const formatMean=(mean:number|null)=>mean===null?"—":mean.toFixed(2);
export function GradeExplorer({courseId}:{courseId:string}){
  const [detail,setDetail]=useState<GradeDetail|null>(null),[term,setTerm]=useState(""),[instructor,setInstructor]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController(),params=new URLSearchParams();let active=true;if(term)params.set("term",term);if(instructor)params.set("instructor",instructor);fetch(`/api/grades/${encodeURIComponent(courseId)}?${params}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("Grade data is temporarily unavailable");return response.json() as Promise<GradeDetail>;}).then(value=>{if(active){setDetail(value);setError("");}}).catch(cause=>{if(active&&cause.name!=="AbortError")setError(cause.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;controller.abort();};},[courseId,term,instructor]);
  const buckets=useMemo(()=>letterGradeOrder.map(letter=>({letter,count:detail?.counts[letter]??0})),[detail]),max=Math.max(1,...buckets.map(bucket=>bucket.count));
  return <section className="grade-shell">{error?<div className="catalog-state error" role="alert">{error}</div>:!detail?<div className="catalog-state" role="status">Loading historical grade evidence…</div>:<><section className="grade-hero"><div><span className="kicker">{detail.course.code}</span><h1>{detail.course.title}</h1><p>{detail.term} · {detail.instructor}</p></div><div className="grade-callouts"><article><span>Median grade</span><strong>{detail.median??"—"}</strong></article><article><span>Mean GPA</span><strong>{formatMean(detail.mean)}</strong></article><article><span>Letter grades</span><strong>{detail.sampleSize.toLocaleString()}</strong></article></div></section><section className="grade-controls" aria-label="Grade distribution filters"><label>Term<select value={term} onChange={event=>{setLoading(true);setTerm(event.target.value);}}><option value="">All terms</option>{detail.options.terms.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label>Instructor<select value={instructor} onChange={event=>{setLoading(true);setInstructor(event.target.value);}}><option value="">All instructors</option>{detail.options.instructors.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>{loading?<span role="status">Updating chart…</span>:null}</section><section className="grade-chart-card"><div><span className="kicker">GRADE DISTRIBUTION</span><h2>How students performed</h2><p>Counts reflect historical letter-grade records for the selected cohort.</p></div><div className="grade-chart" role="img" aria-label={`${detail.course.code} grade distribution. ${buckets.map(bucket=>`${bucket.letter}: ${bucket.count}`).join(", ")}`}>
    {buckets.map(bucket=><div className="grade-bar" key={bucket.letter}><div><i style={{height:`${bucket.count/max*100}%`}}/><span>{bucket.count.toLocaleString()}</span></div><b>{bucket.letter}</b></div>)}</div><details className="grade-table"><summary>View accessible grade table</summary><table><caption>{detail.course.code} historical letter-grade counts</caption><thead><tr><th>Grade</th><th>Count</th><th>Percent</th></tr></thead><tbody>{buckets.map(bucket=><tr key={bucket.letter}><td>{bucket.letter}</td><td>{bucket.count.toLocaleString()}</td><td>{detail.sampleSize?`${(bucket.count/detail.sampleSize*100).toFixed(1)}%`:"—"}</td></tr>)}</tbody></table></details></section><aside className="grade-provenance"><div><span className="kicker">DATA RECEIPT</span><h2>Transparent by design</h2><p>Updated {new Date(detail.updatedAt).toLocaleString()}. This historical dataset is transitional and non-official.</p></div><dl><div><dt>Source</dt><dd><a href={detail.provenance.sourceUrl}>{detail.provenance.sourceName} ↗</a></dd></div><div><dt>Official source</dt><dd>No — transitional adapter</dd></div><div><dt>Aggregation</dt><dd>Course · instructor · term</dd></div></dl></aside></>}</section>;
}
