"use client";
import { createContext,useContext,useEffect,useMemo,useState,type ReactNode } from "react";
import type { CatalogRecord } from "../lib/data/types";
import { defaultScheduleConstraints,defaultSchedulePreferences,formatMeeting,generateConflictFreeSchedules,scheduleSettingsFromParams,scheduleShareParams,scheduleToIcs,timeMinutes,type GeneratedSchedule,type ScheduleConstraints,type SchedulePreferences } from "../lib/real-schedule";
import { CloudPlanManager } from "./cloud-plan-manager";
import type { PlanPayload } from "../lib/plans";
import { trackProductEvent } from "../lib/client-analytics";

type StudioContextValue={selected:CatalogRecord[];toggle:(record:CatalogRecord)=>void;replace:(records:CatalogRecord[])=>void};
const StudioContext=createContext<StudioContextValue|null>(null),storageKey="courseflow-real-section-pool-v1";
const useStudio=()=>{const value=useContext(StudioContext);if(!value)throw new Error("Schedule studio provider missing");return value;};

export function ScheduleStudioProvider({children}:{children:ReactNode}){
  const [selected,setSelected]=useState<CatalogRecord[]>([]);
  useEffect(()=>{const timer=window.setTimeout(()=>{const shared=new URLSearchParams(window.location.search).get("sections")?.split(",").filter(Boolean).slice(0,18);if(shared?.length){const params=new URLSearchParams({term:"Fall 2026"});shared.forEach(id=>params.append("id",id));void fetch(`/api/catalog?${params}`).then(response=>response.json()).then((data:{records?:CatalogRecord[]})=>{if(data.records?.length){const byId=new Map(data.records.map(record=>[record.id,record]));const restored=shared.map(id=>byId.get(id)).filter((record):record is CatalogRecord=>Boolean(record));setSelected(restored);localStorage.setItem(storageKey,JSON.stringify(restored));}});return;}try{const saved=JSON.parse(localStorage.getItem(storageKey)??"[]");if(Array.isArray(saved))setSelected(saved.slice(0,18));}catch{}},0);return()=>window.clearTimeout(timer);},[]);
  const toggle=(record:CatalogRecord)=>setSelected(current=>{const next=current.some(item=>item.id===record.id)?current.filter(item=>item.id!==record.id):current.length>=18?current:[...current,record];localStorage.setItem(storageKey,JSON.stringify(next));return next;});
  const replace=(records:CatalogRecord[])=>{const next=records.slice(0,18);setSelected(next);localStorage.setItem(storageKey,JSON.stringify(next));};
  return <StudioContext.Provider value={{selected,toggle,replace}}>{children}</StudioContext.Provider>;
}

export function SectionPoolButton({record}:{record:CatalogRecord}){const {selected,toggle}=useStudio(),active=selected.some(item=>item.id===record.id);return <button className={`pool-button ${active?"active":""}`} aria-pressed={active} onClick={()=>toggle(record)}>{active?"Remove from schedule pool":"Add to schedule pool"}</button>;}

const weekdays=["Monday","Tuesday","Wednesday","Thursday","Friday"];
function WeeklyOptionCalendar({schedule}:{schedule:GeneratedSchedule}){
  const blocks=schedule.sections.flatMap((section,sectionIndex)=>section.meetings.flatMap((meeting,meetingIndex)=>meeting.days.flatMap(day=>{
    const column=weekdays.indexOf(day),start=timeMinutes(meeting.startTime),end=timeMinutes(meeting.endTime);
    return column<0||start===null||end===null?[]:[{section,meeting,column,start,end,key:`${section.id}-${meetingIndex}-${day}`,tone:sectionIndex%6}];
  })));
  return <div className="real-week" aria-label="Weekly calendar">
    <div className="real-week-days"><span/>{weekdays.map(day=><b key={day}>{day.slice(0,3)}</b>)}</div>
    <div className="real-week-grid">
      <div className="real-week-times">{[8,10,12,14,16,18,20].map(hour=><span key={hour}>{hour>12?hour-12:hour} {hour>=12?"PM":"AM"}</span>)}</div>
      {weekdays.map((day,column)=><div className="real-day-column" key={day} style={{left:`${16.666+column*16.666}%`}}/>)}
      {blocks.map(block=><div className={`real-meeting tone-${block.tone}`} key={block.key} style={{left:`${16.666+block.column*16.666}%`,top:`${Math.max(0,(block.start-480)/720*100)}%`,height:`${Math.max(5,(block.end-block.start)/720*100)}%`}} title={formatMeeting(block.meeting)}><b>{block.section.code}</b><span>{block.section.sectionNumber}</span></div>)}
    </div>
  </div>;
}

export function ScheduleStudio({accountsEnabled=false}:{accountsEnabled?:boolean}){
  const {selected,toggle,replace}=useStudio(),[generated,setGenerated]=useState<ReturnType<typeof generateConflictFreeSchedules>>([]),[attempted,setAttempted]=useState(false),[open,setOpen]=useState(true),[preferences,setPreferences]=useState<SchedulePreferences>(defaultSchedulePreferences),[constraints,setConstraints]=useState<ScheduleConstraints>(defaultScheduleConstraints),[shareMessage,setShareMessage]=useState(""),groups=useMemo(()=>{const result=new Map<string,CatalogRecord[]>();for(const item of selected)result.set(item.code,[...(result.get(item.code)??[]),item]);return result;},[selected]),comparisons=[...groups.entries()].filter(([,items])=>items.length>1);
  useEffect(()=>{const timer=window.setTimeout(()=>{const settings=scheduleSettingsFromParams(new URLSearchParams(window.location.search));setPreferences(settings.preferences);setConstraints(settings.constraints);},0);return()=>window.clearTimeout(timer);},[]);
  const generate=()=>{const results=generateConflictFreeSchedules(selected,preferences,constraints);setGenerated(results);setAttempted(true);trackProductEvent(results.length?"schedule_generated":"constraint_no_results",{sections:selected.length,courses:groups.size,options:results.length});};
  const updatePreference=<K extends keyof SchedulePreferences>(key:K,value:SchedulePreferences[K])=>setPreferences(current=>({...current,[key]:value}));
  const updateConstraint=<K extends keyof ScheduleConstraints>(key:K,value:ScheduleConstraints[K])=>setConstraints(current=>({...current,[key]:value}));
  const share=async()=>{const url=new URL(window.location.href);url.pathname="/";url.search=scheduleShareParams(selected.map(section=>section.id),preferences,constraints).toString();await navigator.clipboard.writeText(url.toString());trackProductEvent("schedule_shared",{sections:selected.length});setShareMessage("Share link and optimizer settings copied.");window.setTimeout(()=>setShareMessage(""),2200);};
  const exportCalendar=(schedule:GeneratedSchedule)=>{const blob=new Blob([scheduleToIcs(schedule)],{type:"text/calendar"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="courseflow-fall-2026.ics";anchor.click();URL.revokeObjectURL(url);trackProductEvent("calendar_exported",{sections:schedule.sections.length});};
  const current:PlanPayload={kind:"real-sections",sectionIds:selected.map(section=>section.id),savedAt:new Date().toISOString()};
  const restore=async(payload:PlanPayload)=>{if(payload.kind!=="real-sections")return;const params=new URLSearchParams({term:"Fall 2026"});payload.sectionIds.forEach(id=>params.append("id",id));const response=await fetch(`/api/catalog?${params}`,{cache:"no-store"});if(!response.ok)throw new Error("Catalog unavailable");const data=await response.json() as {records:CatalogRecord[]};if(data.records.length!==payload.sectionIds.length)throw new Error("Some saved sections are no longer available");const byId=new Map(data.records.map(record=>[record.id,record]));replace(payload.sectionIds.map(id=>byId.get(id)).filter((record):record is CatalogRecord=>Boolean(record)));setGenerated([]);setAttempted(false);setOpen(true);};
  const cloud=<CloudPlanManager configured={accountsEnabled} current={current} onRestore={restore} planKind="real-sections" placement="real-plans"/>;
  if(!selected.length)return <>{cloud}<section className="schedule-studio empty"><div><span className="kicker">REAL SCHEDULE STUDIO</span><h2>Build from actual sections.</h2><p>Add sections from the catalog to compare alternatives and generate conflict-free combinations. Signed-in plans can be restored from Cloud plans.</p></div></section></>;
  if(!open)return <>{cloud}<button className="studio-launcher" onClick={()=>setOpen(true)} aria-label={`Open schedule studio with ${selected.length} selected sections`}><b>{selected.length}</b><span>Open schedule studio</span></button></>;
  return <>{cloud}<section className="schedule-studio drawer" aria-labelledby="studio-title"><header><div><span className="kicker">REAL SCHEDULE STUDIO</span><h2 id="studio-title">{selected.length} section{selected.length===1?"":"s"} · {groups.size} course{groups.size===1?"":"s"}</h2><p>Hard constraints remove invalid options. Preferences rank every remaining schedule with reconciled evidence.</p></div><div className="studio-actions"><button className="minimize-studio" onClick={()=>setOpen(false)} aria-label="Minimize schedule studio">Minimize</button><button className="generate-real" onClick={generate}>Generate ranked schedules</button></div></header>
    <div className="pool-chips">{selected.map(section=><button key={section.id} onClick={()=>toggle(section)} aria-label={`Remove ${section.code} section ${section.sectionNumber}`}><b>{section.code}</b> · {section.sectionNumber}<span aria-hidden="true">×</span></button>)}</div>
    <section className="optimizer-controls" aria-label="Schedule constraints and preferences"><div><h3>Hard constraints</h3><label>No classes before<select value={constraints.noClassesBefore??""} onChange={event=>updateConstraint("noClassesBefore",event.target.value?Number(event.target.value):null)}><option value="">Any time</option><option value="540">9:00 AM</option><option value="600">10:00 AM</option><option value="660">11:00 AM</option></select></label><label>No classes after<select value={constraints.noClassesAfter??""} onChange={event=>updateConstraint("noClassesAfter",event.target.value?Number(event.target.value):null)}><option value="">Any time</option><option value="900">3:00 PM</option><option value="1020">5:00 PM</option><option value="1080">6:00 PM</option></select></label><div className="blocked-days">{weekdays.map(day=><label key={day}><input type="checkbox" checked={constraints.blockedDays.includes(day)} onChange={event=>updateConstraint("blockedDays",event.target.checked?[...constraints.blockedDays,day]:constraints.blockedDays.filter(value=>value!==day))}/>No {day.slice(0,3)}</label>)}</div></div><div><h3>Ranking preferences</h3><label>Preferred start<select value={preferences.earliestStart} onChange={event=>updatePreference("earliestStart",Number(event.target.value))}><option value="480">8:00 AM</option><option value="540">9:00 AM</option><option value="600">10:00 AM</option></select></label><label>Preferred finish<select value={preferences.latestEnd} onChange={event=>updatePreference("latestEnd",Number(event.target.value))}><option value="900">3:00 PM</option><option value="1020">5:00 PM</option><option value="1080">6:00 PM</option></select></label><div className="optimizer-toggles">{([["protectLunch","Protect lunch"],["preferCompact","Compact days"],["preferDaysOff","Prefer days off"],["prioritizeSeats","Open seats"],["prioritizeGrades","Historical signal"]] as Array<[keyof SchedulePreferences,string]>).map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(preferences[key])} onChange={event=>updatePreference(key,event.target.checked as never)}/>{label}</label>)}</div></div></section>
    <div className="studio-share"><button onClick={()=>void share()}>Copy shareable schedule link</button><span role="status" aria-live="polite">{shareMessage}</span></div>
    {comparisons.length?<section className="section-comparisons"><h3>Section comparison</h3>{comparisons.map(([code,items])=><div className="comparison-group" key={code}><b>{code}</b><div role="table" aria-label={`${code} section comparison`}>{items.map(item=><div role="row" key={item.id}><span role="cell">Section {item.sectionNumber}</span><span role="cell">{item.meetings.map(formatMeeting).join(" · ")||"Meeting TBA"}</span><span role="cell">{item.capacity-item.enrolled>0?`${item.capacity-item.enrolled} open`:"Full"}</span><span role="cell">{item.medianGrade?`${item.medianGrade} median`:"Grades collecting"}</span></div>)}</div></div>)}</section>:null}
    {attempted?<section className="generated-real" aria-live="polite"><h3>{generated.length?`${generated.length} ranked conflict-free option${generated.length===1?"":"s"}`:"No schedule satisfies every hard constraint"}</h3>{generated.length?<div>{generated.map((schedule,index)=><article key={schedule.id}><header><span>Option {index+1}</span><strong>{schedule.score}/100</strong></header><WeeklyOptionCalendar schedule={schedule}/><details className="score-proof"><summary>Why this score?</summary>{schedule.contributions.map(item=><div key={item.label}><b>{item.label}</b><strong>+{item.points}</strong><span>{item.detail}</span></div>)}<footer>Total: {schedule.contributions.reduce((sum,item)=>sum+item.points,0)}/100</footer></details><div>{schedule.sections.map(section=><div key={section.id}><b>{section.code} · {section.sectionNumber}</b><span>{section.meetings.map(formatMeeting).join(" · ")||"Meeting TBA"}</span></div>)}</div><button className="export-ics" onClick={()=>exportCalendar(schedule)}>Export calendar (.ics)</button><footer>{schedule.openSeats} open seats · {schedule.daysOnCampus} days on campus · no detected overlaps</footer></article>)}</div>:<p>Relax a hard constraint or add another section alternative, then generate again.</p>}</section>:null}
    <p className="studio-disclosure">Schedule pool is stored on this device. Verify final meeting and enrollment details in Berkeley’s official Class Schedule before enrolling.</p>
  </section></>;
}
