import { createHmac,timingSafeEqual } from "node:crypto";

export type NotificationSettings={emailEnabled:boolean;frequency:"immediate"|"hourly";quietStart:number;quietEnd:number;timezone:string;unsubscribed:boolean};
export const defaultNotificationSettings:NotificationSettings={emailEnabled:false,frequency:"immediate",quietStart:22,quietEnd:7,timezone:"America/Los_Angeles",unsubscribed:false};
export function isQuietHour(now:Date,settings:Pick<NotificationSettings,"quietStart"|"quietEnd"|"timezone">){let hour:number;try{hour=Number(new Intl.DateTimeFormat("en-US",{timeZone:settings.timezone,hour:"2-digit",hourCycle:"h23"}).format(now));}catch{hour=Number(new Intl.DateTimeFormat("en-US",{timeZone:"America/Los_Angeles",hour:"2-digit",hourCycle:"h23"}).format(now));}return settings.quietStart===settings.quietEnd?false:settings.quietStart<settings.quietEnd?hour>=settings.quietStart&&hour<settings.quietEnd:hour>=settings.quietStart||hour<settings.quietEnd;}
export function normalizeNotificationSettings(value:Record<string,unknown>):Omit<NotificationSettings,"unsubscribed">{const quietStart=Number(value.quietStart),quietEnd=Number(value.quietEnd),frequency=value.frequency==="hourly"?"hourly":"immediate",timezone=typeof value.timezone==="string"&&value.timezone.length<=64?value.timezone:"America/Los_Angeles";if(!Number.isInteger(quietStart)||quietStart<0||quietStart>23||!Number.isInteger(quietEnd)||quietEnd<0||quietEnd>23)throw new Error("Quiet hours must be whole hours from 0 to 23");try{new Intl.DateTimeFormat("en-US",{timeZone:timezone}).format();}catch{throw new Error("Unsupported timezone");}return{emailEnabled:value.emailEnabled===true,frequency,quietStart,quietEnd,timezone};}
function secret(){return process.env.COURSEFLOW_UNSUBSCRIBE_SECRET||process.env.COURSEFLOW_REFRESH_SECRET||"";}
export function createUnsubscribeToken(userId:string){if(!secret())throw new Error("Unsubscribe signing secret is not configured");const encoded=Buffer.from(userId).toString("base64url"),signature=createHmac("sha256",secret()).update(encoded).digest("base64url");return`${encoded}.${signature}`;}
export function verifyUnsubscribeToken(token:string){const [encoded,signature]=token.split(".");if(!encoded||!signature||!secret())return null;const expected=createHmac("sha256",secret()).update(encoded).digest("base64url"),a=Buffer.from(signature),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))return null;try{return Buffer.from(encoded,"base64url").toString();}catch{return null;}}
