import { randomUUID } from "node:crypto";
import { and,desc,eq,inArray,sql } from "drizzle-orm";
import { getDb } from "../db";
import { courses,enrollmentAlerts,enrollmentSnapshots,enrollmentWatches,notificationPreferences,sections,userProfiles } from "../db/schema";
import type { CourseFlowIdentity } from "./auth";
import { createUnsubscribeToken,defaultNotificationSettings,isQuietHour,normalizeNotificationSettings,type NotificationSettings } from "./notifications";

export type EnrollmentWatch={id:string;sectionId:string;code:string;title:string;sectionNumber:string;enrolled:number;capacity:number;waitlisted:number;emailEnabled:boolean;createdAt:string};
export type UserAlert={id:string;sectionId:string;kind:string;message:string;read:boolean;emailStatus:string;emailAttempts:number;createdAt:string};

export async function ensureWatchSchema(){const db=getDb();for(const statement of [sql`CREATE TABLE IF NOT EXISTS enrollment_watches (id text PRIMARY KEY,user_id text NOT NULL REFERENCES user_profiles(id),section_id text NOT NULL REFERENCES sections(id),notify_open boolean NOT NULL DEFAULT true,notify_waitlist boolean NOT NULL DEFAULT true,email_enabled boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL)`,sql`CREATE UNIQUE INDEX IF NOT EXISTS enrollment_watches_user_section_idx ON enrollment_watches(user_id,section_id)`,sql`CREATE INDEX IF NOT EXISTS enrollment_watches_section_idx ON enrollment_watches(section_id)`,sql`CREATE TABLE IF NOT EXISTS enrollment_alerts (id text PRIMARY KEY,watch_id text NOT NULL REFERENCES enrollment_watches(id),user_id text NOT NULL REFERENCES user_profiles(id),section_id text NOT NULL REFERENCES sections(id),kind text NOT NULL,message text NOT NULL,dedupe_key text NOT NULL UNIQUE,read_at timestamptz,email_status text NOT NULL DEFAULT 'not_requested',email_attempts integer NOT NULL DEFAULT 0,provider_message_id text,last_email_attempt_at timestamptz,created_at timestamptz NOT NULL)`,sql`ALTER TABLE enrollment_alerts ADD COLUMN IF NOT EXISTS email_attempts integer NOT NULL DEFAULT 0`,sql`ALTER TABLE enrollment_alerts ADD COLUMN IF NOT EXISTS provider_message_id text`,sql`ALTER TABLE enrollment_alerts ADD COLUMN IF NOT EXISTS last_email_attempt_at timestamptz`,sql`CREATE INDEX IF NOT EXISTS enrollment_alerts_user_time_idx ON enrollment_alerts(user_id,created_at)`,sql`CREATE TABLE IF NOT EXISTS notification_preferences (user_id text PRIMARY KEY REFERENCES user_profiles(id),email_enabled boolean NOT NULL DEFAULT false,frequency text NOT NULL DEFAULT 'immediate',quiet_start integer NOT NULL DEFAULT 22,quiet_end integer NOT NULL DEFAULT 7,timezone text NOT NULL DEFAULT 'America/Los_Angeles',unsubscribed_at timestamptz,updated_at timestamptz NOT NULL)`])await db.execute(statement);}
async function profile(identity:CourseFlowIdentity){await ensureWatchSchema();const db=getDb(),id=`clerk:${identity.userId}`,now=new Date();await db.insert(userProfiles).values({id,clerkUserId:identity.userId,email:identity.email,priorities:{},createdAt:now,updatedAt:now}).onConflictDoUpdate({target:userProfiles.clerkUserId,set:{email:identity.email,updatedAt:now}});await db.insert(notificationPreferences).values({userId:id,updatedAt:now}).onConflictDoNothing();return id;}
function settingsFrom(row:typeof notificationPreferences.$inferSelect|undefined):NotificationSettings{return row?{emailEnabled:row.emailEnabled,frequency:row.frequency==="hourly"?"hourly":"immediate",quietStart:row.quietStart,quietEnd:row.quietEnd,timezone:row.timezone,unsubscribed:Boolean(row.unsubscribedAt)}:defaultNotificationSettings;}
export async function listWatchState(identity:CourseFlowIdentity){const db=getDb(),userId=await profile(identity);const [watches,alerts,pref]=await Promise.all([db.select({watch:enrollmentWatches,section:sections,course:courses}).from(enrollmentWatches).innerJoin(sections,eq(enrollmentWatches.sectionId,sections.id)).innerJoin(courses,eq(sections.courseId,courses.id)).where(eq(enrollmentWatches.userId,userId)).orderBy(desc(enrollmentWatches.createdAt)),db.select().from(enrollmentAlerts).where(eq(enrollmentAlerts.userId,userId)).orderBy(desc(enrollmentAlerts.createdAt)).limit(50),db.select().from(notificationPreferences).where(eq(notificationPreferences.userId,userId)).limit(1)]);return{settings:settingsFrom(pref[0]),watches:watches.map(({watch,section,course}):EnrollmentWatch=>({id:watch.id,sectionId:section.id,code:`${course.subject} ${course.number}`,title:course.title,sectionNumber:section.sectionNumber,enrolled:section.enrolled,capacity:section.capacity,waitlisted:section.waitlisted,emailEnabled:watch.emailEnabled,createdAt:watch.createdAt.toISOString()})),alerts:alerts.map((alert):UserAlert=>({id:alert.id,sectionId:alert.sectionId,kind:alert.kind,message:alert.message,read:Boolean(alert.readAt),emailStatus:alert.emailStatus,emailAttempts:alert.emailAttempts,createdAt:alert.createdAt.toISOString()}))};}
export async function updateNotificationSettings(identity:CourseFlowIdentity,input:Record<string,unknown>){const db=getDb(),userId=await profile(identity),settings=normalizeNotificationSettings(input),now=new Date();await db.update(notificationPreferences).set({...settings,unsubscribedAt:settings.emailEnabled?null:undefined,updatedAt:now}).where(eq(notificationPreferences.userId,userId));return listWatchState(identity);}
export async function unsubscribeUser(userId:string){await ensureWatchSchema();await getDb().update(notificationPreferences).set({emailEnabled:false,unsubscribedAt:new Date(),updatedAt:new Date()}).where(eq(notificationPreferences.userId,userId));}
export async function addWatch(identity:CourseFlowIdentity,sectionId:string,emailEnabled:boolean){const db=getDb(),userId=await profile(identity),section=(await db.select({id:sections.id}).from(sections).where(eq(sections.id,sectionId)).limit(1))[0];if(!section)throw new Error("Section not found");const id=`${userId}:${randomUUID()}`,createdAt=new Date();await db.insert(enrollmentWatches).values({id,userId,sectionId,emailEnabled,createdAt}).onConflictDoUpdate({target:[enrollmentWatches.userId,enrollmentWatches.sectionId],set:{emailEnabled}});return listWatchState(identity);}
export async function removeWatch(identity:CourseFlowIdentity,sectionId:string){const db=getDb(),userId=await profile(identity),owned=await db.select({id:enrollmentWatches.id}).from(enrollmentWatches).where(and(eq(enrollmentWatches.userId,userId),eq(enrollmentWatches.sectionId,sectionId)));for(const watch of owned)await db.delete(enrollmentAlerts).where(and(eq(enrollmentAlerts.watchId,watch.id),eq(enrollmentAlerts.userId,userId)));await db.delete(enrollmentWatches).where(and(eq(enrollmentWatches.userId,userId),eq(enrollmentWatches.sectionId,sectionId)));return listWatchState(identity);}
export async function markAlertsRead(identity:CourseFlowIdentity){const db=getDb(),userId=await profile(identity);await db.update(enrollmentAlerts).set({readAt:new Date()}).where(and(eq(enrollmentAlerts.userId,userId),sql`${enrollmentAlerts.readAt} IS NULL`));return listWatchState(identity);}

function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]!);}
async function sendEmail(email:string,alert:{id:string;message:string;userId:string}){const key=process.env.RESEND_API_KEY,from=process.env.COURSEFLOW_ALERT_FROM;if(!key||!from)return{status:"not_configured",providerId:null};const base=process.env.COURSEFLOW_PUBLIC_URL||"https://berkeley-courseflow.zesty-mole-4007.chatgpt.site",unsubscribe=`${base}/notifications/unsubscribe?token=${encodeURIComponent(createUnsubscribeToken(alert.userId))}`,response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json","idempotency-key":`courseflow-alert-${alert.id}`},body:JSON.stringify({from,to:[email],subject:"CourseFlow enrollment alert",text:`${alert.message}\n\nManage alerts: ${base}/catalog\nUnsubscribe: ${unsubscribe}`,html:`<div style="font-family:Arial,sans-serif;max-width:560px"><h1 style="color:#0b1f3a">A Berkeley enrollment signal changed</h1><p>${escapeHtml(alert.message)}</p><p><a href="${base}/catalog">Review your watchlist</a></p><hr><p style="font-size:12px;color:#667"><a href="${unsubscribe}">Unsubscribe from CourseFlow emails</a></p></div>`})});let body:{id?:string}|null=null;try{body=await response.json() as {id?:string};}catch{}return{status:response.ok?"sent":"failed",providerId:body?.id??null};}
async function deliverPendingEmails(){const db=getDb(),now=new Date(),rows=await db.select({alert:enrollmentAlerts,email:userProfiles.email,pref:notificationPreferences}).from(enrollmentAlerts).innerJoin(userProfiles,eq(enrollmentAlerts.userId,userProfiles.id)).innerJoin(notificationPreferences,eq(enrollmentAlerts.userId,notificationPreferences.userId)).where(and(inArray(enrollmentAlerts.emailStatus,["pending","failed","deferred"]),sql`${enrollmentAlerts.emailAttempts} < 3`)).orderBy(enrollmentAlerts.createdAt).limit(100);let sent=0,deferred=0,failed=0;for(const row of rows){const settings=settingsFrom(row.pref);if(!row.email||!settings.emailEnabled||settings.unsubscribed){await db.update(enrollmentAlerts).set({emailStatus:"not_requested"}).where(eq(enrollmentAlerts.id,row.alert.id));continue;}if(isQuietHour(now,settings)||settings.frequency==="hourly"&&now.getMinutes()>=15){await db.update(enrollmentAlerts).set({emailStatus:"deferred"}).where(eq(enrollmentAlerts.id,row.alert.id));deferred++;continue;}const result=await sendEmail(row.email,{id:row.alert.id,message:row.alert.message,userId:row.alert.userId}),attempts=row.alert.emailAttempts+1;await db.update(enrollmentAlerts).set({emailStatus:result.status,emailAttempts:attempts,providerMessageId:result.providerId,lastEmailAttemptAt:now}).where(eq(enrollmentAlerts.id,row.alert.id));if(result.status==="sent")sent++;else failed++;}return{sent,deferred,failed};}
export async function evaluateEnrollmentAlerts(){await ensureWatchSchema();const db=getDb(),watches=await db.select({watch:enrollmentWatches,email:userProfiles.email,section:sections,course:courses,pref:notificationPreferences}).from(enrollmentWatches).innerJoin(userProfiles,eq(enrollmentWatches.userId,userProfiles.id)).innerJoin(notificationPreferences,eq(enrollmentWatches.userId,notificationPreferences.userId)).innerJoin(sections,eq(enrollmentWatches.sectionId,sections.id)).innerJoin(courses,eq(sections.courseId,courses.id));let created=0;for(const item of watches){const snapshots=await db.select().from(enrollmentSnapshots).where(eq(enrollmentSnapshots.sectionId,item.section.id)).orderBy(desc(enrollmentSnapshots.observedAt)).limit(2);if(snapshots.length<2)continue;const [latest,previous]=snapshots,available=Math.max(0,latest.capacity-latest.enrolled),previousAvailable=Math.max(0,previous.capacity-previous.enrolled);let kind="",message="";if(item.watch.notifyOpen&&available>0&&previousAvailable===0){kind="seat_opened";message=`${item.course.subject} ${item.course.number} section ${item.section.sectionNumber} now has ${available} open seat${available===1?"":"s"}.`;}else if(item.watch.notifyWaitlist&&latest.waitlisted<previous.waitlisted){kind="waitlist_moved";message=`${item.course.subject} ${item.course.number} section ${item.section.sectionNumber} waitlist moved from ${previous.waitlisted} to ${latest.waitlisted}.`;}if(!kind)continue;const dedupeKey=`${item.watch.id}:${kind}:${latest.observedAt.toISOString()}`,id=randomUUID(),settings=settingsFrom(item.pref),emailRequested=item.watch.emailEnabled&&settings.emailEnabled&&!settings.unsubscribed;const inserted=await db.insert(enrollmentAlerts).values({id,watchId:item.watch.id,userId:item.watch.userId,sectionId:item.section.id,kind,message,dedupeKey,emailStatus:emailRequested?"pending":"not_requested",createdAt:new Date()}).onConflictDoNothing().returning({id:enrollmentAlerts.id});if(inserted.length)created++;}const delivery=await deliverPendingEmails();return{watches:watches.length,created,emailed:delivery.sent,deferred:delivery.deferred,failed:delivery.failed};}
