import { randomUUID } from "node:crypto";
import { and,desc,eq,sql } from "drizzle-orm";
import { getDb } from "../db";
import { courses,enrollmentAlerts,enrollmentSnapshots,enrollmentWatches,sections,userProfiles } from "../db/schema";
import type { CourseFlowIdentity } from "./auth";

export type EnrollmentWatch={id:string;sectionId:string;code:string;title:string;sectionNumber:string;enrolled:number;capacity:number;waitlisted:number;emailEnabled:boolean;createdAt:string};
export type UserAlert={id:string;sectionId:string;kind:string;message:string;read:boolean;emailStatus:string;createdAt:string};

export async function ensureWatchSchema(){const db=getDb();for(const statement of [sql`CREATE TABLE IF NOT EXISTS enrollment_watches (id text PRIMARY KEY,user_id text NOT NULL REFERENCES user_profiles(id),section_id text NOT NULL REFERENCES sections(id),notify_open boolean NOT NULL DEFAULT true,notify_waitlist boolean NOT NULL DEFAULT true,email_enabled boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL)`,sql`CREATE UNIQUE INDEX IF NOT EXISTS enrollment_watches_user_section_idx ON enrollment_watches(user_id,section_id)`,sql`CREATE INDEX IF NOT EXISTS enrollment_watches_section_idx ON enrollment_watches(section_id)`,sql`CREATE TABLE IF NOT EXISTS enrollment_alerts (id text PRIMARY KEY,watch_id text NOT NULL REFERENCES enrollment_watches(id),user_id text NOT NULL REFERENCES user_profiles(id),section_id text NOT NULL REFERENCES sections(id),kind text NOT NULL,message text NOT NULL,dedupe_key text NOT NULL UNIQUE,read_at timestamptz,email_status text NOT NULL DEFAULT 'not_requested',created_at timestamptz NOT NULL)`,sql`CREATE INDEX IF NOT EXISTS enrollment_alerts_user_time_idx ON enrollment_alerts(user_id,created_at)`])await db.execute(statement);}
async function profile(identity:CourseFlowIdentity){await ensureWatchSchema();const db=getDb(),id=`clerk:${identity.userId}`,now=new Date();await db.insert(userProfiles).values({id,clerkUserId:identity.userId,email:identity.email,priorities:{},createdAt:now,updatedAt:now}).onConflictDoUpdate({target:userProfiles.clerkUserId,set:{email:identity.email,updatedAt:now}});return id;}
export async function listWatchState(identity:CourseFlowIdentity){const db=getDb(),userId=await profile(identity);const watches=await db.select({watch:enrollmentWatches,section:sections,course:courses}).from(enrollmentWatches).innerJoin(sections,eq(enrollmentWatches.sectionId,sections.id)).innerJoin(courses,eq(sections.courseId,courses.id)).where(eq(enrollmentWatches.userId,userId)).orderBy(desc(enrollmentWatches.createdAt));const alerts=await db.select().from(enrollmentAlerts).where(eq(enrollmentAlerts.userId,userId)).orderBy(desc(enrollmentAlerts.createdAt)).limit(50);return{watches:watches.map(({watch,section,course}):EnrollmentWatch=>({id:watch.id,sectionId:section.id,code:`${course.subject} ${course.number}`,title:course.title,sectionNumber:section.sectionNumber,enrolled:section.enrolled,capacity:section.capacity,waitlisted:section.waitlisted,emailEnabled:watch.emailEnabled,createdAt:watch.createdAt.toISOString()})),alerts:alerts.map((alert):UserAlert=>({id:alert.id,sectionId:alert.sectionId,kind:alert.kind,message:alert.message,read:Boolean(alert.readAt),emailStatus:alert.emailStatus,createdAt:alert.createdAt.toISOString()}))};}
export async function addWatch(identity:CourseFlowIdentity,sectionId:string,emailEnabled:boolean){const db=getDb(),userId=await profile(identity),section=(await db.select({id:sections.id}).from(sections).where(eq(sections.id,sectionId)).limit(1))[0];if(!section)throw new Error("Section not found");const id=`${userId}:${randomUUID()}`,createdAt=new Date();await db.insert(enrollmentWatches).values({id,userId,sectionId,emailEnabled,createdAt}).onConflictDoUpdate({target:[enrollmentWatches.userId,enrollmentWatches.sectionId],set:{emailEnabled}});return listWatchState(identity);}
export async function removeWatch(identity:CourseFlowIdentity,sectionId:string){const db=getDb(),userId=await profile(identity),owned=await db.select({id:enrollmentWatches.id}).from(enrollmentWatches).where(and(eq(enrollmentWatches.userId,userId),eq(enrollmentWatches.sectionId,sectionId)));for(const watch of owned)await db.delete(enrollmentAlerts).where(and(eq(enrollmentAlerts.watchId,watch.id),eq(enrollmentAlerts.userId,userId)));await db.delete(enrollmentWatches).where(and(eq(enrollmentWatches.userId,userId),eq(enrollmentWatches.sectionId,sectionId)));return listWatchState(identity);}
export async function markAlertsRead(identity:CourseFlowIdentity){const db=getDb(),userId=await profile(identity);await db.update(enrollmentAlerts).set({readAt:new Date()}).where(and(eq(enrollmentAlerts.userId,userId),sql`${enrollmentAlerts.readAt} IS NULL`));return listWatchState(identity);}

async function sendEmail(email:string,subject:string,message:string){const key=process.env.RESEND_API_KEY,from=process.env.COURSEFLOW_ALERT_FROM;if(!key||!from)return"not_configured";const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({from,to:[email],subject,text:message})});return response.ok?"sent":"failed";}
export async function evaluateEnrollmentAlerts(){await ensureWatchSchema();const db=getDb(),watches=await db.select({watch:enrollmentWatches,email:userProfiles.email,section:sections,course:courses}).from(enrollmentWatches).innerJoin(userProfiles,eq(enrollmentWatches.userId,userProfiles.id)).innerJoin(sections,eq(enrollmentWatches.sectionId,sections.id)).innerJoin(courses,eq(sections.courseId,courses.id));let created=0,emailed=0;for(const item of watches){const snapshots=await db.select().from(enrollmentSnapshots).where(eq(enrollmentSnapshots.sectionId,item.section.id)).orderBy(desc(enrollmentSnapshots.observedAt)).limit(2);if(snapshots.length<2)continue;const [latest,previous]=snapshots,available=Math.max(0,latest.capacity-latest.enrolled),previousAvailable=Math.max(0,previous.capacity-previous.enrolled);let kind="",message="";if(item.watch.notifyOpen&&available>0&&previousAvailable===0){kind="seat_opened";message=`${item.course.subject} ${item.course.number} section ${item.section.sectionNumber} now has ${available} open seat${available===1?"":"s"}.`;}else if(item.watch.notifyWaitlist&&latest.waitlisted<previous.waitlisted){kind="waitlist_moved";message=`${item.course.subject} ${item.course.number} section ${item.section.sectionNumber} waitlist moved from ${previous.waitlisted} to ${latest.waitlisted}.`;}if(!kind)continue;const dedupeKey=`${item.watch.id}:${kind}:${latest.observedAt.toISOString()}`,id=randomUUID(),now=new Date();const inserted=await db.insert(enrollmentAlerts).values({id,watchId:item.watch.id,userId:item.watch.userId,sectionId:item.section.id,kind,message,dedupeKey,emailStatus:item.watch.emailEnabled?"pending":"not_requested",createdAt:now}).onConflictDoNothing().returning({id:enrollmentAlerts.id});if(!inserted.length)continue;created++;if(item.watch.emailEnabled&&item.email){const status=await sendEmail(item.email,"CourseFlow enrollment alert",message);await db.update(enrollmentAlerts).set({emailStatus:status}).where(eq(enrollmentAlerts.id,id));if(status==="sent")emailed++;}}return{watches:watches.length,created,emailed};}
