import { desc,sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { academicPrograms,courses,enrollmentAlerts,enrollmentSnapshots,enrollmentWatches,refreshRuns,sections,sources } from "../../../db/schema";
import { ensureAcademicSchema } from "../../../lib/academic";
import { operationalLog } from "../../../lib/observability";

export async function GET(){
  const checkedAt=new Date().toISOString(),started=Date.now();
  if(process.env.COURSEFLOW_DATA_MODE!=="neon"||!process.env.DATABASE_URL)return Response.json({status:"degraded",checkedAt,mode:"snapshot",database:{status:"unavailable",latencyMs:null},catalog:{sections:0,courses:0,snapshots:0,lastRefresh:null,freshness:"unknown"},alerts:{watches:0,generated:0,emailConfigured:false},refresh:{runs:0,successRate:null,lastStatus:null,history:[]},academic:{programs:0,lastVerified:null,sourceUrl:null},checks:[{name:"Production data adapter",status:"warn",detail:"Snapshot mode active"},{name:"Refresh reliability",status:"warn",detail:"Run history is available in production mode"},{name:"Official degree source",status:"warn",detail:"Verified requirements are available in production mode"}]},{headers:{"cache-control":"public, max-age=30"}});
  try{
    await ensureAcademicSchema();
    const db=getDb(),queryStarted=Date.now();
    const [[sectionCount],[courseCount],[snapshotCount],[watchCount],[alertCount],[programCount],[program],[source],runs]=await Promise.all([
      db.select({count:sql<number>`count(*)`}).from(sections),db.select({count:sql<number>`count(*)`}).from(courses),db.select({count:sql<number>`count(*)`}).from(enrollmentSnapshots),db.select({count:sql<number>`count(*)`}).from(enrollmentWatches),db.select({count:sql<number>`count(*)`}).from(enrollmentAlerts),db.select({count:sql<number>`count(*)`}).from(academicPrograms),db.select({retrievedAt:academicPrograms.retrievedAt,sourceUrl:academicPrograms.sourceUrl}).from(academicPrograms).orderBy(desc(academicPrograms.retrievedAt)).limit(1),db.select({retrievedAt:sources.retrievedAt}).from(sources).orderBy(desc(sources.retrievedAt)).limit(1),db.select().from(refreshRuns).orderBy(desc(refreshRuns.startedAt)).limit(20)
    ]);
    const latencyMs=Date.now()-queryStarted,lastRefresh=source?.retrievedAt.toISOString()??null,ageMinutes=lastRefresh?(Date.now()-Date.parse(lastRefresh))/60_000:Infinity,freshness=ageMinutes<=30?"live":ageMinutes<=120?"aging":"stale",successes=runs.filter(run=>run.status==="success").length,successRate=runs.length?Math.round(successes/runs.length*100):null,status=freshness==="stale"||successRate!==null&&successRate<90?"degraded":"operational";
    return Response.json({status,checkedAt,mode:"neon",responseMs:Date.now()-started,database:{status:"connected",latencyMs},catalog:{sections:Number(sectionCount.count),courses:Number(courseCount.count),snapshots:Number(snapshotCount.count),lastRefresh,freshness,ageMinutes:Number.isFinite(ageMinutes)?Math.round(ageMinutes):null},alerts:{watches:Number(watchCount.count),generated:Number(alertCount.count),emailConfigured:Boolean(process.env.RESEND_API_KEY&&process.env.COURSEFLOW_ALERT_FROM)},refresh:{runs:runs.length,successRate,lastStatus:runs[0]?.status??null,lastDurationMs:runs[0]?.durationMs??null,history:runs.slice(0,8).map(run=>({status:run.status,startedAt:run.startedAt.toISOString(),durationMs:run.durationMs,records:run.records,detail:run.detail}))},academic:{programs:Number(programCount.count),lastVerified:program?.retrievedAt.toISOString()??null,sourceUrl:program?.sourceUrl??null},checks:[{name:"Neon database",status:"pass",detail:`Connected in ${latencyMs}ms`},{name:"Catalog freshness",status:freshness==="live"?"pass":"warn",detail:lastRefresh?`Last observation ${Math.round(ageMinutes)} minutes ago`:"No observation"},{name:"Refresh reliability",status:successRate===null?"warn":successRate>=90?"pass":"warn",detail:successRate===null?"History begins with the next run":`${successRate}% success across ${runs.length} retained runs`},{name:"Official degree source",status:Number(programCount.count)>0?"pass":"warn",detail:Number(programCount.count)>0?`Berkeley CS B.A. requirements verified ${program?.retrievedAt.toISOString()??""}`:"Awaiting first official catalog ingestion"},{name:"Email delivery",status:process.env.RESEND_API_KEY&&process.env.COURSEFLOW_ALERT_FROM?"pass":"warn",detail:process.env.RESEND_API_KEY&&process.env.COURSEFLOW_ALERT_FROM?"Provider configured":"Awaiting verified sender credentials"}]},{headers:{"cache-control":"public, max-age=30, stale-while-revalidate=60"}});
  }catch(error){operationalLog("error","health_check_failed",{error:error instanceof Error?error.message:"Unknown error"});return Response.json({status:"outage",checkedAt,error:"Health data unavailable"},{status:503,headers:{"cache-control":"no-store"}});}
}
